name: debug on macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    #- uses: actions/checkout@v4
    #- name: Build
    # run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup debug session with sshx
      run: curl -sSf https://sshx.io/get | sh -s run
    #- name: Setup Debug Session
    #  uses: csexton/debugger-action@master
